version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      - 'POSTGRES_DB=nnpia'
      - 'POSTGRES_PASSWORD=nnpia'
      - 'POSTGRES_USER=nnpia'
    ports:
      - "5432:5432"

