server:
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nnpia
    username: nnpia
    password: nnpia
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

jwt:
  secret: 3fgzGcfXn7LRuLmrtSkKh2fHsUArJ8ZxgNV0hmH5zluCZtc+YPYzQKWRJbzQyBNr